# Generated by Django 5.1 on 2024-08-27 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=255)),
                ('project_desc', models.TextField()),
                ('tech_stack', models.JSONField()),
                ('project_img', models.ImageField(upload_to='projects/')),
                ('reverse', models.BooleanField(default=False)),
            ],
        ),
    ]
